#############################################################################
# Makefile for building: libkalkulacka.so
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  kalkulacka\kalkulacka.pro
# Template: app
# Command: C:\qtcrator\5.12.0\android_armv7\bin\qmake.exe -o Makefile kalkulacka\kalkulacka.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang
CXX           = C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -D__ANDROID_API__=16 -target armv7-none-linux-androideabi -gcc-toolchain C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -DANDROID_HAS_WSTRING --sysroot=C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sysroot -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/cxx-stl/llvm-libc++/include -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/android/support/include -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/cxx-stl/llvm-libc++abi/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -marm -O0 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -D__ANDROID_API__=16 -target armv7-none-linux-androideabi -gcc-toolchain C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -DANDROID_HAS_WSTRING --sysroot=C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sysroot -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/cxx-stl/llvm-libc++/include -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/android/support/include -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/cxx-stl/llvm-libc++abi/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -g -marm -O0 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -Ikalkulacka -I. -IC:\qtcrator\5.12.0\android_armv7\include -IC:\qtcrator\5.12.0\android_armv7\include\QtWidgets -IC:\qtcrator\5.12.0\android_armv7\include\QtGui -IC:\qtcrator\5.12.0\android_armv7\include\QtCore -I. -I. -IC:\qtcrator\5.12.0\android_armv7\mkspecs\android-clang
QMAKE         = C:\qtcrator\5.12.0\android_armv7\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\qtcrator\5.12.0\android_armv7\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\qtcrator\5.12.0\android_armv7\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
TAR           = 
COMPRESS      = 
DISTNAME      = libkalkulacka.so1.0.0
DISTDIR = C:\Users\Dominika\Desktop\skola\MTE\kalkulacka\MTE\.tmp\libkalkulacka.so1.0.0
LINK          = C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -D__ANDROID_API__=16 -target armv7-none-linux-androideabi -gcc-toolchain C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -Wl,--exclude-libs,libgcc.a
LFLAGS        = --sysroot=C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/platforms/android-16/arch-arm/ -Wl,-soname,libkalkulacka.so -Wl,-rpath=C:/qtcrator/5.12.0/android_armv7/lib -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -LC:/qtcrator/5.12.0/android_armv7/lib -lQt5Widgets -Lc:\Utils\Android\android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -lQt5Gui -lQt5Core -lGLESv2  -LC:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++.so.16 -llog -lz -lm -ldl -lc
AR            = C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ar cqs
RANLIB        = C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ranlib
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = kalkulacka\main.cpp \
		kalkulacka\mainwindow.cpp \
		kalkulacka\controller.cpp \
		kalkulacka\lexicalanalyzer.cpp \
		kalkulacka\postfixnotation.cpp \
		kalkulacka\windowsec.cpp qrc_img.cpp \
		moc_mainwindow.cpp \
		moc_windowsec.cpp
OBJECTS       = main.obj \
		mainwindow.obj \
		controller.obj \
		lexicalanalyzer.obj \
		postfixnotation.obj \
		windowsec.obj \
		qrc_img.obj \
		moc_mainwindow.obj \
		moc_windowsec.obj
DIST          = kalkulacka\android\AndroidManifest.xml \
		kalkulacka\android\gradle\wrapper\gradle-wrapper.jar \
		kalkulacka\android\gradlew \
		kalkulacka\android\res\values\libs.xml \
		kalkulacka\android\build.gradle \
		kalkulacka\android\gradle\wrapper\gradle-wrapper.properties \
		kalkulacka\android\gradlew.bat kalkulacka\mainwindow.h \
		kalkulacka\controller.h \
		kalkulacka\postfixnotation.h \
		kalkulacka\lexicalanalyzer.h \
		kalkulacka\windowsec.h kalkulacka\main.cpp \
		kalkulacka\mainwindow.cpp \
		kalkulacka\controller.cpp \
		kalkulacka\lexicalanalyzer.cpp \
		kalkulacka\postfixnotation.cpp \
		kalkulacka\windowsec.cpp
QMAKE_TARGET  = libkalkulacka.so
DESTDIR       = 
TARGET        = libkalkulacka.so


first: all
####### Build rules

libkalkulacka.so: ui_mainwindow.h ui_windowsec.h ui_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kalkulacka\kalkulacka.pro C:\qtcrator\5.12.0\android_armv7\mkspecs\android-clang\qmake.conf C:\qtcrator\5.12.0\android_armv7\mkspecs\features\spec_pre.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\common\unix.conf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\common\linux.conf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\common\sanitize.conf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\common\gcc-base.conf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\common\gcc-base-unix.conf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\common\clang.conf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\qdevice.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\device_config.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\common\android-base-head.conf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\qconfig.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3danimation.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dcore.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dextras.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dinput.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquick.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3drender.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_androidextras.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_concurrent.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_core.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_core_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_edid_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_egl_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_gamepad.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_gui.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_gui_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_help.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_help_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_input_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_location.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_location_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_multimedia.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_network.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_network_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_nfc.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_opengl.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_positioning.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_positioningquick.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_positioningquick_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_printsupport.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qml.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qml_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qmltest.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quick.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quick_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickshapes_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_repparser.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_scxml.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_sensors.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_service_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_sql.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_sql_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_svg.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_svg_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_testlib.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_texttospeech.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_texttospeech_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_uitools.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_webchannel.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_websockets.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_webview.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_webview_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_widgets.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_xml.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_xml_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\qt_functions.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\qt_config.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\common\android-base-tail.conf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\android-clang\qmake.conf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\spec_post.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\exclusive_builds.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\toolchain.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\default_pre.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\resolve_config.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\default_post.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\qml_debug.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\android\android.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\android\android_deployment_settings.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\warn_on.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\qt.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\resources.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\moc.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\unix\opengl.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\uic.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\unix\thread.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\qmake_use.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\file_copies.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\testcase_targets.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\exceptions.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\yacc.prf \
		C:\qtcrator\5.12.0\android_armv7\mkspecs\features\lex.prf \
		kalkulacka\kalkulacka.pro \
		kalkulacka\img.qrc \
		C:\qtcrator\5.12.0\android_armv7\lib\libQt5Widgets.prl \
		C:\qtcrator\5.12.0\android_armv7\lib\libQt5Gui.prl \
		C:\qtcrator\5.12.0\android_armv7\lib\libQt5Core.prl
	$(QMAKE) -o Makefile kalkulacka\kalkulacka.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug"
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\spec_pre.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\common\unix.conf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\common\linux.conf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\common\sanitize.conf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\common\gcc-base.conf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\common\gcc-base-unix.conf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\common\clang.conf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\qdevice.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\device_config.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\common\android-base-head.conf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\qconfig.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3danimation.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dcore.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dextras.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dinput.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquick.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3drender.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_androidextras.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_concurrent.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_core.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_core_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_edid_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_egl_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_gamepad.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_gui.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_gui_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_help.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_help_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_input_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_location.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_location_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_multimedia.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_network.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_network_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_nfc.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_opengl.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_positioning.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_positioningquick.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_positioningquick_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_printsupport.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qml.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qml_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qmltest.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quick.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quick_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickshapes_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_repparser.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_repparser_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_scxml.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_sensors.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_service_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_sql.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_sql_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_svg.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_svg_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_testlib.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_texttospeech.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_texttospeech_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_uitools.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_vulkan_support_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_webchannel.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_websockets.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_webview.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_webview_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_widgets.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_xml.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_xml_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\qt_functions.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\qt_config.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\common\android-base-tail.conf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\android-clang\qmake.conf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\spec_post.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\exclusive_builds.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\toolchain.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\default_pre.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\resolve_config.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\default_post.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\qml_debug.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\android\android.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\android\android_deployment_settings.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\warn_on.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\qt.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\resources.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\moc.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\unix\opengl.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\uic.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\unix\thread.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\qmake_use.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\file_copies.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\testcase_targets.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\exceptions.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\yacc.prf:
C:\qtcrator\5.12.0\android_armv7\mkspecs\features\lex.prf:
kalkulacka\kalkulacka.pro:
kalkulacka\img.qrc:
C:\qtcrator\5.12.0\android_armv7\lib\libQt5Widgets.prl:
C:\qtcrator\5.12.0\android_armv7\lib\libQt5Gui.prl:
C:\qtcrator\5.12.0\android_armv7\lib\libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile kalkulacka\kalkulacka.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE


all: Makefile libkalkulacka.so

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents kalkulacka\img.qrc $(DISTDIR)\
	$(COPY_FILE) --parents C:\qtcrator\5.12.0\android_armv7\mkspecs\features\data\dummy.cpp $(DISTDIR)\
	$(COPY_FILE) --parents kalkulacka\mainwindow.h kalkulacka\controller.h kalkulacka\postfixnotation.h kalkulacka\lexicalanalyzer.h kalkulacka\windowsec.h $(DISTDIR)\
	$(COPY_FILE) --parents kalkulacka\main.cpp kalkulacka\mainwindow.cpp kalkulacka\controller.cpp kalkulacka\lexicalanalyzer.cpp kalkulacka\postfixnotation.cpp kalkulacka\windowsec.cpp $(DISTDIR)\
	$(COPY_FILE) --parents kalkulacka\mainwindow.ui kalkulacka\windowsec.ui kalkulacka\dialog.ui $(DISTDIR)\


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_img.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_img.cpp
qrc_img.cpp: kalkulacka\img.qrc \
		C:\qtcrator\5.12.0\android_armv7\bin\rcc.exe \
		kalkulacka\img\bckps.png \
		kalkulacka\img\change.png \
		kalkulacka\img\calcu.png
	C:\qtcrator\5.12.0\android_armv7\bin\rcc.exe -name img kalkulacka\img.qrc -o qrc_img.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: C:\qtcrator\5.12.0\android_armv7\mkspecs\features\data\dummy.cpp
	C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -D__ANDROID_API__=16 -target armv7-none-linux-androideabi -gcc-toolchain C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -DANDROID_HAS_WSTRING --sysroot=C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sysroot -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/cxx-stl/llvm-libc++/include -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/android/support/include -isystem C:\Users\Dominika\Downloads\android-ndk-r18b-windows-x86_64\android-ndk-r18b/sources/cxx-stl/llvm-libc++abi/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -g -marm -O0 -Wall -W -dM -E -o moc_predefs.h C:\qtcrator\5.12.0\android_armv7\mkspecs\features\data\dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_windowsec.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_windowsec.cpp
moc_mainwindow.cpp: C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\QMainWindow \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qmainwindow.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtwidgetsglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtguiglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtcore-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsystemdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qprocessordetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtypeinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsysinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlogging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qflags.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbasicatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qgenericatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobalstatic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmutex.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnumeric.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qversiontagging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtgui-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtwidgets-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qwindowdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnamespace.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstring.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qchar.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrefcount.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qarraydata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringliteral.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringview.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringbuilder.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiterator.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhashfunctions.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpair.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearraylist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qregexp.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringmatcher.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcoreevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qscopedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmetatype.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmargins.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpaintdevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrect.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsize.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpoint.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpalette.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qcolor.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qrgb.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qrgba64.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qbrush.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvector.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qmatrix.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpolygon.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qregion.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdatastream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiodevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qline.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtransform.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpainterpath.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qimage.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpixelformat.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpixmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qshareddata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhash.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfont.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfontmetrics.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfontinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qsizepolicy.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qcursor.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qkeysequence.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvariant.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdebug.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtextstream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlocale.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qset.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qurl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qurlquery.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qfile.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qfiledevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qvector2d.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtouchdevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtabwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qicon.h \
		kalkulacka\mainwindow.h \
		moc_predefs.h \
		C:\qtcrator\5.12.0\android_armv7\bin\moc.exe
	C:\qtcrator\5.12.0\android_armv7\bin\moc.exe $(DEFINES) --include C:/Users/Dominika/Desktop/skola/MTE/kalkulacka/MTE/moc_predefs.h -IC:/qtcrator/5.12.0/android_armv7/mkspecs/android-clang -IC:/Users/Dominika/Desktop/skola/MTE/kalkulacka/MTE/kalkulacka -IC:/qtcrator/5.12.0/android_armv7/include -IC:/qtcrator/5.12.0/android_armv7/include/QtWidgets -IC:/qtcrator/5.12.0/android_armv7/include/QtGui -IC:/qtcrator/5.12.0/android_armv7/include/QtCore -I. -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/sources/cxx-stl/llvm-libc++/include -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/sources/android/support/include -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/sources/cxx-stl/llvm-libc++abi/include -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/7.0.2/include -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/sysroot/usr/include kalkulacka\mainwindow.h -o moc_mainwindow.cpp

moc_windowsec.cpp: C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\QMainWindow \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qmainwindow.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtwidgetsglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtguiglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtcore-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsystemdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qprocessordetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtypeinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsysinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlogging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qflags.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbasicatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qgenericatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobalstatic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmutex.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnumeric.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qversiontagging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtgui-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtwidgets-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qwindowdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnamespace.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstring.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qchar.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrefcount.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qarraydata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringliteral.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringview.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringbuilder.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiterator.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhashfunctions.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpair.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearraylist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qregexp.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringmatcher.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcoreevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qscopedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmetatype.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmargins.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpaintdevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrect.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsize.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpoint.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpalette.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qcolor.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qrgb.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qrgba64.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qbrush.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvector.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qmatrix.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpolygon.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qregion.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdatastream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiodevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qline.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtransform.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpainterpath.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qimage.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpixelformat.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpixmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qshareddata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhash.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfont.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfontmetrics.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfontinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qsizepolicy.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qcursor.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qkeysequence.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvariant.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdebug.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtextstream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlocale.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qset.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qurl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qurlquery.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qfile.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qfiledevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qvector2d.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtouchdevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtabwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qicon.h \
		kalkulacka\windowsec.h \
		moc_predefs.h \
		C:\qtcrator\5.12.0\android_armv7\bin\moc.exe
	C:\qtcrator\5.12.0\android_armv7\bin\moc.exe $(DEFINES) --include C:/Users/Dominika/Desktop/skola/MTE/kalkulacka/MTE/moc_predefs.h -IC:/qtcrator/5.12.0/android_armv7/mkspecs/android-clang -IC:/Users/Dominika/Desktop/skola/MTE/kalkulacka/MTE/kalkulacka -IC:/qtcrator/5.12.0/android_armv7/include -IC:/qtcrator/5.12.0/android_armv7/include/QtWidgets -IC:/qtcrator/5.12.0/android_armv7/include/QtGui -IC:/qtcrator/5.12.0/android_armv7/include/QtCore -I. -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/sources/cxx-stl/llvm-libc++/include -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/sources/android/support/include -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/sources/cxx-stl/llvm-libc++abi/include -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/7.0.2/include -IC:/Users/Dominika/Downloads/android-ndk-r18b-windows-x86_64/android-ndk-r18b/sysroot/usr/include kalkulacka\windowsec.h -o moc_windowsec.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_windowsec.h ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_windowsec.h ui_dialog.h
ui_mainwindow.h: kalkulacka\mainwindow.ui \
		C:\qtcrator\5.12.0\android_armv7\bin\uic.exe
	C:\qtcrator\5.12.0\android_armv7\bin\uic.exe kalkulacka\mainwindow.ui -o ui_mainwindow.h

ui_windowsec.h: kalkulacka\windowsec.ui \
		C:\qtcrator\5.12.0\android_armv7\bin\uic.exe
	C:\qtcrator\5.12.0\android_armv7\bin\uic.exe kalkulacka\windowsec.ui -o ui_windowsec.h

ui_dialog.h: kalkulacka\dialog.ui \
		C:\qtcrator\5.12.0\android_armv7\bin\uic.exe
	C:\qtcrator\5.12.0\android_armv7\bin\uic.exe kalkulacka\dialog.ui -o ui_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.obj: kalkulacka\main.cpp kalkulacka\mainwindow.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\QMainWindow \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qmainwindow.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtwidgetsglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtguiglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtcore-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsystemdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qprocessordetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtypeinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsysinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlogging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qflags.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbasicatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qgenericatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobalstatic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmutex.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnumeric.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qversiontagging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtgui-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtwidgets-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qwindowdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnamespace.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstring.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qchar.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrefcount.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qarraydata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringliteral.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringview.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringbuilder.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiterator.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhashfunctions.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpair.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearraylist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qregexp.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringmatcher.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcoreevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qscopedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmetatype.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmargins.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpaintdevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrect.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsize.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpoint.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpalette.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qcolor.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qrgb.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qrgba64.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qbrush.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvector.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qmatrix.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpolygon.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qregion.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdatastream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiodevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qline.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtransform.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpainterpath.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qimage.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpixelformat.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpixmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qshareddata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhash.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfont.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfontmetrics.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfontinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qsizepolicy.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qcursor.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qkeysequence.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvariant.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdebug.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtextstream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlocale.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qset.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qurl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qurlquery.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qfile.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qfiledevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qvector2d.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtouchdevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtabwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qicon.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\QApplication \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qapplication.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcoreapplication.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qeventloop.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qdesktopwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qguiapplication.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj kalkulacka\main.cpp

mainwindow.obj: kalkulacka\mainwindow.cpp kalkulacka\mainwindow.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\QMainWindow \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qmainwindow.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtwidgetsglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtguiglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtcore-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsystemdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qprocessordetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtypeinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsysinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlogging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qflags.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbasicatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qgenericatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobalstatic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmutex.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnumeric.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qversiontagging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtgui-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtwidgets-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qwindowdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnamespace.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstring.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qchar.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrefcount.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qarraydata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringliteral.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringview.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringbuilder.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiterator.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhashfunctions.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpair.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearraylist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qregexp.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringmatcher.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcoreevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qscopedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmetatype.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmargins.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpaintdevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrect.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsize.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpoint.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpalette.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qcolor.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qrgb.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qrgba64.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qbrush.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvector.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qmatrix.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpolygon.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qregion.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdatastream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiodevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qline.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtransform.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpainterpath.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qimage.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpixelformat.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpixmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qshareddata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhash.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfont.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfontmetrics.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfontinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qsizepolicy.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qcursor.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qkeysequence.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvariant.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdebug.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtextstream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlocale.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qset.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qurl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qurlquery.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qfile.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qfiledevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qvector2d.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtouchdevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtabwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qicon.h \
		ui_mainwindow.h \
		kalkulacka\controller.h \
		kalkulacka\postfixnotation.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QStack \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstack.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QDebug \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QChar \
		kalkulacka\lexicalanalyzer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QVector \
		kalkulacka\windowsec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.obj kalkulacka\mainwindow.cpp

controller.obj: kalkulacka\controller.cpp kalkulacka\controller.h \
		kalkulacka\postfixnotation.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QStack \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstack.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvector.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtcore-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsystemdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qprocessordetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtypeinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsysinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlogging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qflags.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbasicatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qgenericatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobalstatic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmutex.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnumeric.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qversiontagging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiterator.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrefcount.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qarraydata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhashfunctions.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstring.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qchar.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnamespace.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringliteral.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringview.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringbuilder.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpair.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearraylist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qregexp.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringmatcher.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpoint.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QDebug \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdebug.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhash.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtextstream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiodevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcoreevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qscopedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmetatype.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlocale.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvariant.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qshareddata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qset.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QChar \
		kalkulacka\lexicalanalyzer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QVector
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.obj kalkulacka\controller.cpp

lexicalanalyzer.obj: kalkulacka\lexicalanalyzer.cpp kalkulacka\lexicalanalyzer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QVector \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvector.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtcore-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsystemdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qprocessordetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtypeinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsysinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlogging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qflags.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbasicatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qgenericatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobalstatic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmutex.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnumeric.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qversiontagging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiterator.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrefcount.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qarraydata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhashfunctions.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstring.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qchar.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnamespace.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringliteral.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringview.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringbuilder.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpair.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearraylist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qregexp.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringmatcher.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpoint.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdebug.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhash.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtextstream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiodevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcoreevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qscopedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmetatype.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlocale.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvariant.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qshareddata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qset.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QtDebug \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lexicalanalyzer.obj kalkulacka\lexicalanalyzer.cpp

postfixnotation.obj: kalkulacka\postfixnotation.cpp kalkulacka\postfixnotation.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QStack \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstack.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvector.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtcore-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsystemdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qprocessordetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtypeinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsysinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlogging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qflags.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbasicatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qgenericatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobalstatic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmutex.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnumeric.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qversiontagging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiterator.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrefcount.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qarraydata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhashfunctions.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstring.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qchar.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnamespace.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringliteral.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringview.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringbuilder.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpair.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearraylist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qregexp.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringmatcher.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpoint.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QDebug \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdebug.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhash.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtextstream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiodevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcoreevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qscopedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmetatype.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlocale.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvariant.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qshareddata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qset.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QChar \
		kalkulacka\lexicalanalyzer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QVector
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o postfixnotation.obj kalkulacka\postfixnotation.cpp

windowsec.obj: kalkulacka\windowsec.cpp kalkulacka\windowsec.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\QMainWindow \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qmainwindow.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtwidgetsglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtguiglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobal.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qconfig.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtcore-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsystemdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qprocessordetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtypeinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsysinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlogging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qflags.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbasicatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qgenericatomic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qglobalstatic.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmutex.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnumeric.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qversiontagging.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtgui-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtwidgets-config.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qwindowdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qnamespace.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstring.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qchar.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrefcount.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qarraydata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringliteral.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringview.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringbuilder.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qalgorithms.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiterator.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhashfunctions.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpair.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qbytearraylist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringlist.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qregexp.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qstringmatcher.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcoreevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qscopedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmetatype.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qobject_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmargins.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpaintdevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qrect.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsize.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qpoint.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpalette.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qcolor.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qrgb.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qrgba64.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qbrush.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvector.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qmatrix.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpolygon.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qregion.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdatastream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qiodevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qline.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtransform.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpainterpath.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qimage.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpixelformat.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qpixmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qshareddata.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qhash.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfont.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfontmetrics.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qfontinfo.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qsizepolicy.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qcursor.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qkeysequence.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qevent.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qvariant.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qmap.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qdebug.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qtextstream.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qlocale.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qset.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qurl.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qurlquery.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qfile.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\qfiledevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qvector2d.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qtouchdevice.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtWidgets\qtabwidget.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtGui\qicon.h \
		ui_windowsec.h \
		kalkulacka\mainwindow.h \
		C:\qtcrator\5.12.0\android_armv7\include\QtCore\QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o windowsec.obj kalkulacka\windowsec.cpp

qrc_img.obj: qrc_img.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_img.obj qrc_img.cpp

moc_mainwindow.obj: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.obj moc_mainwindow.cpp

moc_windowsec.obj: moc_windowsec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_windowsec.obj moc_windowsec.cpp

####### Install

install_target: first FORCE
	@if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a mkdir $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a & if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a exit 1
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

